CREATE TABLE IF NOT EXISTS players (
   player_id INT AUTO_INCREMENT PRIMARY KEY,
   alias VARCHAR(32) NOT NULL,
   level INT NOT NULL DEFAULT 1,
  -- first_seen DATE NOT NULL DEFAULT CURRENT_DATE,
   last_connection TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   connections INT NOT NULL DEFAULT 1,
   guid VARCHAR(36) NOT NULL UNIQUE
) ENGINE=InnoDB;