CREATE TABLE IF NOT EXISTS players (
   player_id INT AUTO_INCREMENT PRIMARY KEY,
   alias VARCHAR(32) NOT NULL,
   level INT NOT NULL DEFAULT 1,
   first_seen TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   last_connection TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   connections INT NOT NULL DEFAULT 0,
   guid VARCHAR(36) NOT NULL UNIQUE
) ENGINE=InnoDB;